version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - 'MONGODB_USER=user'
      - 'MONGODB_PASS=nekoneko2255tlabportal'
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - ./data/db:/data/db
    command: mongod

  front:
    build:
      args:
        env: "$ENV"
      context: .
      dockerfile: front/Dockerfile-no-build
    volumes:
      - ./front:/src
    ports:
      - "$FRONT_PORT:80"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    links:
      - mongodb
    ports:
      - "$API_PORT:80"
    volumes:
      - ./api:/src

