version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - ./data/db:/data/db
      #- ./mongo/init/:/docker-entrypoint-initdb.d/

  front:
    build:
      args:
        REACT_APP_ENV: "$ENV"
        REACT_APP_REDIRECT_URI: "$SLACK_REDIRECT_URI"
      context: .
      dockerfile: front/Dockerfile
    volumes:
      - ./front:/src
    ports:
      - "$FRONT_PORT:80"

  api:
    build:
      args:
        APP_ENV: "$ENV"
        SLACK_REDIRECT_URI: "$SLACK_REDIRECT_URI"
        MONGO_URI: "$MONGO_URI"
      context: .
      dockerfile: api/Dockerfile
    links:
      - mongodb
    ports:
      - "$API_PORT:3000"
    volumes:
      - ./api:/src
